name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./supply-chain-management/pom.xml
          mvn clean package -f ./production-management/pom.xml
          mvn clean package -f ./product-management/pom.xml
          mvn clean package -f ./financial-management/pom.xml

      - name: Docker Build and push for SupplyChainManagement
        uses: docker/build-push-action@v4
        with:
          context: ./supply-chain-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/supply-chain-management:latest
            ghcr.io/${{ github.repository }}/supply-chain-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductionManagement
        uses: docker/build-push-action@v4
        with:
          context: ./production-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/production-management:latest
            ghcr.io/${{ github.repository }}/production-management:${{ github.ref_name }}
            
      - name: Docker Build and push for ProductManagement
        uses: docker/build-push-action@v4
        with:
          context: ./product-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/product-management:latest
            ghcr.io/${{ github.repository }}/product-management:${{ github.ref_name }}
            
      - name: Docker Build and push for FinancialManagement
        uses: docker/build-push-action@v4
        with:
          context: ./financial-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/financial-management:latest
            ghcr.io/${{ github.repository }}/financial-management:${{ github.ref_name }}
            
