apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-management
  labels:
    app: supply-chain-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-chain-management
  template:
    metadata:
      labels:
        app: supply-chain-management
    spec:
      containers:
        - name: supply-chain-management
          image: "username/supply-chain-management:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
