apiVersion: v1
kind: Service
metadata:
  name: supply-chain-management
  labels:
    app: supply-chain-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: supply-chain-management